apiVersion: v1
kind: Service
metadata:
  name: portfolio-frontend
  namespace: portfolio
  labels:
    app: portfolio
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: portfolio
    component: frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http