version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    networks:
      - portfolio-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - portfolio-network
    command: redis-server --appendonly yes

networks:
  portfolio-network:
    driver: bridge

volumes:
  redis-data: