name: Cleanup Old Resources

on:
  schedule:
    - cron: '0 4 * * 0'  # Weekly on Sunday at 4 AM
  workflow_dispatch:

jobs:
  cleanup-docker:
    name: Cleanup Docker Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old Docker Hub images
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55
        with:
          package-name: 'portfolio-website'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-pre-release-versions: false
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

  cleanup-artifacts:
    name: Cleanup Workflow Artifacts
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete old artifacts
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const maxAge = 7 * 24 * 60 * 60 * 1000; // 7 days
            
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner,
              repo,
              per_page: 100
            });
            
            const now = Date.now();
            for (const artifact of artifacts.data.artifacts) {
              const createdAt = new Date(artifact.created_at).getTime();
              if (now - createdAt > maxAge) {
                await github.rest.actions.deleteArtifact({
                  owner,
                  repo,
                  artifact_id: artifact.id
                });
                console.log(`Deleted artifact: ${artifact.name}`);
              }
            }